# MIT License

# Copyright (c) 2023 Replicable-MARL

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

env: wildfire

env_args:
  map_name: "wildfire"
  max_steps: 100
  size: 17
  alpha: 0.15
  beta: 0.9
  delta_beta: 0.7
  num_agents: 2
  agent_start_positions: [[8, 8], [14, 2]]
  agent_colors: ["red", "blue"]
  initial_fire_size: 3
  cooperative_reward: False
  selfishness_weight: 0.1
  render_selfish_region_boundaries: True
  log_selfish_region_metrics: True
  selfish_region_xmin: [7, 13]
  selfish_region_xmax: [9, 15]
  selfish_region_ymin: [7, 1]
  selfish_region_ymax: [9, 3]

mask_flag: False
global_state_flag: True    # True: fully observable env; False: can use when partial obs there if want to concatenate local obs as one global state. Check if we can keep this False but have no concatenation (partial obs without obs sharing).
opp_action_in_cc: True
agent_level_batch_update: False